#!/bin/bash

# You must set a a variable DICCIONARIO into your
# .bashrc or .zprofile to set the dictory to save
# the diccinaries files.

[ -z $DICCIONARIO ] && notify-send "Please, define a DICCIONARIO varible to continue." && exit 1

# Dmenu is required to use this script

[[ -z $(whereis "dmenu" | cut -d":" -f 2)  ]] && notify-send "You need to install dmenu to use this dictionary." && exit 1

# In case to change the language, use the flag -l or --lang
# and choose it from from the list displayed by dmenu

#IDIOMA=$(cat hola.txt 2&>/dev/null)
#[ -z $IDIOMA ] && notify-send "Please, define a language using the -l or --lang flag." && exit 1

if [[ $1 == "-l" ]] || [[ $1 == "--lang" ]]
then
	IDIOMA=$(echo -e "Español\nEnglish\nPortuguês" | dmenu -p "Please, choose a language " -i -l 3)
	echo "$IDIOMA" > $DICCIONARIO/lang
else
	IDIOMA=$(cat $DICCIONARIO/lang)
fi

# If you don't have you web IP, uncoment this function.
# if you have a better way to know your ip, change it
# and set it as "ip" variable.

IP=$(wget -q -O - ipinfo.io/ip)

Espanol(){
	[[ -d "$DICCIONARIO/$IDIOMA" ]] || mkdir -p "$DICCIONARIO/$IDIOMA"
	PALABRA="$(ls "$DICCIONARIO/$IDIOMA" | dmenu -p "¿Qué palabra buscas? " -i -l 10)"

	if [[ -f $DICCIONARIO/$IDIOMA/$PALABRA ]]
	then
		ACTION=$(dunstify --action="forwardAction,Forward" "Definición RAE de «$PALABRA»" "$(cat $DICCIONARIO/$IDIOMA/$PALABRA)")
	else
		wget -q --user-agent=$IP -O $PALABRA https://dle.rae.es/$PALABRA
		DEFINICION=$(grep 'name="description"' $PALABRA |  sed -e 's/^[^.*]*1//g' -e "s/^/1/" -e "s/\">//")
		#grep -e 'class="tit-significado' -e 'class="significado textonovo"' prueba.html | sed -e 's/<[^>]\+>//g' -e "s/^\s\+//" | sed -n 2p | sed -re 's/\w*/(&)/1' | sed "s/\./\n/"
		echo "$DEFINICION" > $DICCIONARIO/$IDIOMA/$PALABRA
		ACTION=$(dunstify --action="forwardAction,Forward" "Definición RAE de «$PALABRA»" "$(cat $DICCIONARIO/$IDIOMA/$PALABRA)")

	fi

	[[ $ACTION == "forwardAction" ]] && $TERMINAL -e less $DICCIONARIO/$IDIOMA/$PALABRA
	[ -f $PALABRA ] && rm $PALABRA
}

Portugues(){
	[[ -d "$DICCIONARIO/$IDIOMA" ]] || mkdir -p "$DICCIONARIO/$IDIOMA"
	PALABRA="$(ls "$DICCIONARIO/$IDIOMA" | dmenu -p "O qué palavra pesquisas? " -i -l 10)"

	if [[ -f $DICCIONARIO/$IDIOMA/$PALABRA ]]
	then
		ACTION=$(dunstify --action="forwardAction,Forward" "Significado de «$PALABRA»" "$(cat $DICCIONARIO/$IDIOMA/$PALABRA)")
	else
		wget -q --user-agent=$IP -O $PALABRA https://www.dicio.com.br/$PALABRA
		DEFINICION=$(grep -e 'class="tit-significado' -e 'class="significado textonovo"' $PALABRA | sed -e 's/<[^>]\+>//g' -e "s/^\s\+//" | sed -n 2p | sed -re 's/\w*/(&)/1' | sed "s/\./\n/")
		echo "$DEFINICION" > $DICCIONARIO/$IDIOMA/$PALABRA
		ACTION=$(dunstify --action="forwardAction,Forward" "Significado de «$PALABRA»" "$(cat $DICCIONARIO/$IDIOMA/$PALABRA)")
	fi

	[[ $ACTION == "forwardAction" ]] && $TERMINAL -e less $DICCIONARIO/$IDIOMA/$PALABRA
	[ -f $PALABRA ] && rm $PALABRA
}

English(){
	[[ -d "$DICCIONARIO/$IDIOMA" ]] || mkdir -p "$DICCIONARIO/$IDIOMA"
	PALABRA="$(ls "$DICCIONARIO/$IDIOMA" | dmenu -p "Which word are you looking for? " -i -l 10)"

	if [[ -f $DICCIONARIO/$IDIOMA/$PALABRA ]]
	then
		ACTION=$(dunstify --action="forwardAction,Forward" "Definición del Collins Dictionary de «$PALABRA»" "$(cat $DICCIONARIO/$IDIOMA/$PALABRA)")
	else
		wget -q --user-agent=$IP -O $PALABRA https://www.collinsdictionary.com/dictionary/english/$PALABRA
		DEFINICION=`sed -n '/div class="def"/p' $PALABRA | sed -e 's/<[^>]*>//g' -e 's/^\s\+//' | sed '/&nbsp;/d' | sed "s/\b\(.\)/\u\1/g"`
		rm $PALABRA
		echo "$DEFINICION" > $DICCIONARIO/$IDIOMA/$PALABRA
		ACTION=$(dunstify --action="forwardAction,Forward" "Significado de «$PALABRA»" "$(head $DICCIONARIO/$IDIOMA/$PALABRA)")
	fi

	[[ $ACTION == "forwardAction" ]] && $TERMINAL -e less $DICCIONARIO/$IDIOMA/$PALABRA

}



case $IDIOMA in
	Español)
		Espanol;;
	English)
		English;;
	Português)
		Portugues;;
esac
