#!/bin/bash

[[ -z $(whereis "dmenu" | cut -d":" -f 2)  ]] && notify-send "Es necesario instalar dmenu" && exit
DicLang=$(cat $HOME/.local/share/Diccionarios/Idioma.txt)
case $DicLang in
	español)
		DicEspañol;;
	english)
		DicEnglish;;
	português)
		DicPortuguês;;
esac
