#!/bin/bash

palabra=$(ls ~/.local/share/Diccionarios/Español | dmenu -p "¿Qué palabra buscas? " -i -l 10)
dir="$HOME/.local/share/Diccionarios/Español/$palabra"

if [ -f "$dir" ]
then
	notify-send "Definición RAE de «$palabra»" "$(cat ~/.local/share/Diccionarios/Español/$palabra)"
else
	ip=$(cat ~/.local/share/IP/ip)
	wget -q --user-agent=$ip -O $palabra https://dle.rae.es/$palabra
	definicion=$(grep 'name="description"' $palabra |  sed -e 's/^[^.*]*1//g' -e "s/^/1/" -e "s/\">//")
	notify-send "Definición RAE de «$palabra»" "$definicion"
	echo "$definicion" > ~/.local/share/Diccionarios/Español/$palabra
	rm $palabra
fi
